<?php
namespace addons\liuYanBan\controller;


use addons\liuYanBan\model\MsgBoardList;
use addons\liuYanBan\model\MsgBoardReplie;
use app\common\controller\Addon;
use think\Controller;

class Admin extends Addon
{
    public $adminLogin=true;//需要管理员登录才可操作本控制器
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        
    }

    // 留言列表页
    public function index(){
        // 配置
        $config = getAddonInfo();
        if(isset($config['mp_config'])){
            $this->assign('config', $config['mp_config']);
        }
        $this->fetch();
    }

    // 留言列表数据
    public function getList(){
        $bmModel = new MsgBoardList();
        $page = input('page') !== null?input('page'):1;
        $limit = input('limit') !== null?input('limit'):10;

        $result = $bmModel->where(['mpid' => $this->mid]);

        if(!empty(input('name'))){
            $result->where('name', 'like', input('name'));
        }
        if(!empty(input('phone'))){
            $result->where('phone', input('phone'));
        }
        if(!empty(input('status'))){
            $result->where('status', input('status'));
        }
        if(!empty(input('dateline'))){
            $dateline = explode('~', input('dateline'));
            $result->where('dateline', '>=', strtotime($dateline[0].' 00:00:00'))->where('dateline', '<=', strtotime($dateline[1].' 23:59:59'));
        }

        $result->order('dateline DESC')->page($page, $limit);

        ajaxReturn(['data' => $result->select(), 'code' => 0, 'count' => $result->count() ], 1, '提交成功');
    }

    // 留言详情
    public function detail(){
        if(!empty(input('id'))){

            $list = new MsgBoardList();
            $this->assign('data', $list->where(['mb_id' => input('id')])->find());

            $replie = new MsgBoardReplie();
            //$page = input('page') !== null?input('page'):1;
            //$limit = input('limit') !== null?input('limit'):10;
            //$replie = $replie->where(['mb_id' => input('id'), 'mpid' => $this->mid])->order('dateline DESC')->page($page, $limit);
            $replie = $replie->where(['mb_id' => input('id'), 'mpid' => $this->mid])->order('dateline DESC');
            $this->assign('list', $replie->select());

            $this->fetch();
        }
    }

    // 留言回复
    public function msgReplie(){
        if( empty(input('id')) ){
            ajaxMsg('0', '参数错误');
        }
        if( empty(input('content')) ){
            ajaxMsg('0', '回复内容不能为空');
        }
        $list = new MsgBoardList();
        if($list = $list->where('mb_id', input('id'))->find()){
            $admin_info = getAdmin();
            $replie = array(
                'mb_id' => input('id'),
                'mpid' => $this->mid,
                'tuid' => $admin_info['admin_id'],
                'tname' => $admin_info['admin_name'],
                'type' => 0,
                'content' => input('content'),
                'dateline' => time()
            );
            $bmModel = new MsgBoardReplie();
            $bmModel->insert($replie);
            if(!$list['status']){
                $list->save(['status'=> 1], ['mb_id' => input('id')]);
            }
            ajaxMsg('1', '回复成功');
        }else{
            ajaxMsg('0', '该留言不存在或已删除');
        }
    }

    // 删除留言记录
    public function msgDel(){
        if(!empty(input('id'))){
            $bmModel = new MsgBoardList();
            $where['mb_id']=input('id');
            $where['mpid']=$this->mid;
            $bmModel->where($where)->delete();
            $replie = new MsgBoardReplie();
            $replie->where('mb_id', input('id'))->delete();
            ajaxMsg('1', '删除成功');
        }else{
            ajaxMsg('0', '参数错误');
        }
    }

    // 删除回复记录
    public function replieDel(){
        if(!empty(input('id')) && !empty(input('mb_id'))){
            $bmModel = new MsgBoardReplie();
            $where['id'] = input('id');
            $where['mb_id'] = input('mb_id');
            $bmModel->where($where)->delete();
            if($bmModel->where('mb_id', input('mb_id'))->count() <= 0){
                $list = new MsgBoardList();
                $list->save(['status'=> 0], ['mb_id' => input('mb_id')]);
            }
            ajaxMsg('1', '删除成功');
        }else{
            ajaxMsg('0', '参数错误');
        }
    }

}