<?php
namespace addons\liuYanBan\controller;


use addons\liuYanBan\model\MsgBoardList;
use addons\liuYanBan\model\MsgBoardReplie;
use think\Db;
use think\facade\Request;

class Msg extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $this->fetch();
    }

    public function inputs(){
        $this->fetch();
    }

    public function lists(){
        $this->fetch();
    }

    public function submit(){
        if(Request::isAjax()){
            $input = input();
            if(empty($input['title'])){
                return ajaxMsg(0, '标题不能为空');
            }
            if(empty($input['name'])){
                return ajaxMsg(0, '姓名不能为空');
            }
            if(empty($input['phone'])){
                return ajaxMsg(0, '手机不能为空');
            }
            if(empty($input['content'])){
                return ajaxMsg(0, '内容不能为空');
            }

            if(isset($this->mp_config['number']) && $this->mp_config['number'] > 0){
                $bmModel = new MsgBoardList();
                if($bmModel->where('openid', $this->openid)->where('dateline', '>=', mktime(0,0,0,date('m'),date('d'),date('Y')))->where('dateline', '<=', mktime(0, 0, 0, date('m'), date('d')+1, date('Y'))-1)->count() >= $this->mp_config['number']){
                    return ajaxMsg(0, '今日留言次数已上限');
                }
            }

            Db::name('msg_board_list')->insert([
                'mpid' => $this->mid,
                'openid' => $this->openid,
                'nickname' => $this->userInfo['nickname'],
                'avatar' => $this->userInfo['headimgurl'],
                'title' => $input['title'],
                'name' => $input['name'],
                'phone' => $input['phone'],
                'content' => $input['content'],
                'status' => 0,
                'dateline' => time()
            ]);
            return ajaxMsg(1, '提交成功');
        }
        $this->fetch('inputs');
    }

    public function getList(){
        $page = input('page') !== null?input('page'):1;
        $limit = input('limit') !== null?input('limit'):10;
        $boardList = new MsgBoardList();
        $result = $boardList
            ->where(['mpid' => $this->mid, 'openid' => $this->userInfo['openid']])
            ->order('dateline DESC')
            ->page($page, $limit);

        ajaxReturn(['data' => $result->select(), 'code' => 0, 'count' => $result->count() ], 1, '请求成功');
    }

    public function detail(){
        if(!empty(input('id'))){
            $list = new MsgBoardList();
            $this->assign('data', $list->where(['mb_id' => input('id')])->find());

            $replie = new MsgBoardReplie();
            $replie = $replie->where([
                'mb_id' => input('id'), 
                'mpid' => $this->mid
            ])->order('dateline DESC');

            $this->assign('list', $replie->select());

            $this->fetch();
        }
    }

}